### ISSUE TITLE
Golangci-lint Incompatibility with newer versions of Go?

### ISSUE THREAD

**Issue by prometheus1994** [golangci/golangci-lint#663]
I'm running version Go v1.13 and GoLangCI-Lint v1.17.1.
.golangci.yml:
[goconfig.txt](https://github.com/golangci/golangci-lint/files/3580818/goconfig.txt)
Go Version: go1.13 darwin/amd64

I'm experiencing some encoding issues when I run GoLangCI-Lint against my code. 
It looks like the linter is raising issue with the Go standard libraries (strings, fmt, etc.). 

**golangci-lint run output*
main.go:1: /usr/local/go/src/strconv/quote.go:405:12: **ValidString not declared by package utf8 (typecheck)**

main.go:1: /usr/local/go/src/bytes/reader.go:98:18: **DecodeRune not declared by package utf8 (typecheck)**

package main
pkg/cpu/cpu.go:1: /usr/local/go/src/fmt/scan.go:1200:16: **DecodeRuneInString not declared by package utf8 (typecheck)**

package ------
pkg/------/------.go:1: /usr/local/go/src/path/match.go:200:15: **DecodeRuneInString not declared by package utf8 (typecheck)**

**Comment by nnraju31** [comment]
I am having same issue

**Comment by andrewhoff** [comment]
Same here ☝️

**Comment by majst01** [comment]
same

**Comment by nexeck** [comment]
Rebuild golangci-lint with go 1.13 :-)

**Comment by mastertinner** [comment]
This is a duplicate of #659.

**Comment by moul** [comment]
Can a maintainer release a new version built with go 1.13?

The suggested CI method from the README is broken

**Comment by jirfag** [comment]
Hi,
golangci-lint now supports go1.13,
and I've published the [v1.18.0](https://github.com/golangci/golangci-lint/releases/tag/v1.18.0) release today. It's built by go1.13.

**Comment by tobiassjosten** [comment]
I ran into the same problem, updated to 1.19.0 just now, but the errors remain.

```
$ golangci-lint run
apsis/client.go:1: /usr/local/Cellar/go/1.13/libexec/src/strconv/quote.go:405:12: ValidString not declared by package utf8 (typecheck)
package apsis
dogrus/dogrus.go:1: /usr/local/Cellar/go/1.13/libexec/src/strings/strings.go:980:20: DecodeRuneInString not declared by package utf8 (typecheck)
package dogrus
entity/error.go:1: /usr/local/Cellar/go/1.13/libexec/src/strconv/quote.go:405:12: ValidString not declared by package utf8 (typecheck)
package entity
klirr/account.go:1: /usr/local/Cellar/go/1.13/libexec/src/bufio/scan.go:395:19: DecodeRune not declared by package utf8 (typecheck)
package klirr
medley/client.go:1: /usr/local/Cellar/go/1.13/libexec/src/bytes/reader.go:98:18: DecodeRune not declared by package utf8 (typecheck)
package medley
vakt/client.go:1: /usr/local/Cellar/go/1.13/libexec/src/strconv/quote.go:405:12: ValidString not declared by package utf8 (typecheck)
package vakt
```

```
$ brew info golangci-lint
golangci/tap/golangci-lint: stable 1.19.0
Fast linters runner for Go.
https://golangci.com
/usr/local/Cellar/golangci-lint/1.19.0 (5 files, 21.7MB) *
  Built from source on 2019-09-27 at 10:30:26
From: https://github.com/golangci/homebrew-tap/blob/master/Formula/golangci-lint.rb
```

Am I doing something wrong?

**Comment by jirfag** [comment]
Please make a new issue with —version output

**Comment by tobiassjosten** [comment]
My bad! I had a `go get` installation that overrode the `brew` installation. The latter didn't have a `--version` flag, so it wasn't as obvious as it could have been. :) All sorted now and it works fine with 1.19.1. 👍

**Comment by temoto** [comment]
@tpounds of all Github issues related to this problem, this one is the most helpful: contains clear description of error and solution, maybe it's not quite "invalid" as end of thread suggests.

**Comment by tpounds** [comment]
@temoto Agreed. I must have incorrectly categorized this when I was traiging the backlog of open issues. I've updated this issue with a more appropriate label.
